<?php

return [
    'atuacoes-culturais' => [ // Opções para área de atuações culturais
        'artes-cenicas' => [
            'III) Artes Circenses',
            'IV)   Dança',
            'V) Dança',
            'VII)  Teatro e Circo',
            'VIII) Teatro',
            'V) Cultura Hip-Hop',
            'X) Cultura Hip-Hop',
        ],
        'musica' => [
            'VI)   Música',
            'VII) Música',
        ],
        'audiovisual' => [
            'II)  Audiovisual',
            'II) Audiovisual',
            'III) Audiovisual',
        ],
        'artes-visuais' => [
            'I)  Artesanato',
            'I) Artes Visuais',
            'I)   Artes Visuais',
            'II) Artes Visuais',
            'IX) Tecnologia',
            'IX)   Design',
            'X)   Fotografia',
            'VIII)   Moda',
        ],
        'patrimonio-cultural' => [
            'III)   Cultura Popular e Patrimônio',
            'IV) Cultura Popular e Patrimônio',
            'XI)   Gastronomia',
        ],    
        'museu-memoria' => [
            'Museu:Museu e Memória',
        ],
        'humanidades' => [
            'IV) Literatura',
            'V)   Literatura',
            'VI) Literatura',
        ],
    ],
    'header' => [
        'TIPO_INSTRUMENTO',
        'NUMERO_INSTRUMENTO',
        'ANO_INSTRUMENTO',
        'CPF',
        'SEXO',
        'CNPJ',
        'FLAG_CAD_ESTADUAL',
        'SISTEMA_CAD_ESTADUAL',
        'IDENTIFICADOR_CAD_ESTADUAL',
        'FLAG_CAD_MUNICIPAL',
        'SISTEMA_CAD_MUNICIPAL',
        'IDENTIFICADOR_CAD_MUNICIPAL',
        'FLAG_CAD_DISTRITAL',
        'SISTEMA_CAD_DISTRITAL',
        'IDENTIFICADOR_CAD_DISTRITAL',
        'FLAG_CAD_NA_PONTOS_PONTOES',
        'FLAG_CAD_ES_PONTOS_PONTOES',
        'SISTEMA_CAD_ES_PONTOS_PONTOES',
        'IDENTIFICADOR_CAD_ES_PONTOS_PONTOES',
        'FLAG_CAD_SNIIC',
        'SISTEMA_CAD_SNIIC',
        'IDENTIFICADOR_CAD_SNIIC',
        'FLAG_CAD_SALIC',
        'FLAG_CAD_SICAB',
        'FLAG_CAD_OUTROS',
        'SISTEMA_CAD_OUTROS',
        'IDENTIFICADOR_CAD_OUTROS',
        'FLAG_ATUACAO_ARTES_CENICAS',
        'FLAG_ATUACAO_AUDIOVISUAL',
        'FLAG_ATUACAO_MUSICA',
        'FLAG_ATUACAO_ARTES_VISUAIS',
        'FLAG_ATUACAO_PATRIMONIO_CULTURAL',
        'FLAG_ATUACAO_MUSEUS_MEMORIA',
        'FLAG_ATUACAO_HUMANIDADES'
    ],
    "parameters_csv_default" => [
        "status" => '1'
    ],
    'opportunities' => [
        // '80' => [
        //     // 'TIPO_PROPONENTE' => 'field_1098',
        //     // 'TIPO_INSTRUMENTO' => 'Edital',
        //     // 'NUMERO_INSTRUMENTO' => '24',
        //     'ANO_INSTRUMENTO' => '2020',
        //     // 'CPF' => 'field_1104',
        //     // 'SEXO' => 'csvMap',
        //     // 'CNPJ' => 'field_1118',
        //     'FLAG_CAD_ESTADUAL' => 0,            
        //     'FLAG_CAD_MUNICIPAL' => 1,            
        //     'FLAG_CAD_DISTRITAL' => 0,            
        //     'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
        //     'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
        //     'FLAG_CAD_SNIIC' => 0,            
        //     'FLAG_CAD_SALIC' => 0,
        //     'FLAG_CAD_SICAB' => 0,
        //     'FLAG_CAD_OUTROS' => 0,           
        //     'FLAG_ATUACAO_ARTES_CENICAS' => 0,
        //     'FLAG_ATUACAO_AUDIOVISUAL' => 0,
        //     'FLAG_ATUACAO_MUSICA' => 0,
        //     'FLAG_ATUACAO_ARTES_VISUAIS' => 0,
        //     'FLAG_ATUACAO_PATRIMONIO_CULTURAL' => 0,
        //     'FLAG_ATUACAO_MUSEUS_MEMORIA' => 0,
        //     'FLAG_ATUACAO_HUMANIDADES' => 0,
        //     'PESSOA_FISICA' => 'Pessoa Física',
        //     'PESSOA_JURIDICA' => 'Pessoa Jurídica',
        //     'COLETIVO' => 'Coletivo',
        //     // 'DIR_CSV' => 'csv4788.csv',
        // ],
        '90' => [
            'NUMERO_INSTRUMENTO' => '90',
            'CPF' => 'field_4015',
            // 'SEXO' => 'csvMap',
            'CNPJ' => 'field_4014',
            'FLAG_CAD_ESTADUAL' => 1,            
            'FLAG_CAD_MUNICIPAL' => 0,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo',
            // 'DIR_CSV' => 'csv90.csv',                           
        ],
        '91' => [
            'NUMERO_INSTRUMENTO' => '91',
            'CPF' => 'field_4033',
            'SEXO' => 'NULL',
            'CNPJ' => 'field_4034',
            'FLAG_CAD_ESTADUAL' => 1,            
            'FLAG_CAD_MUNICIPAL' => 0,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo',
            // 'DIR_CSV' => 'csv91.csv',                           
        ],
        '92' => [
            'NUMERO_INSTRUMENTO' => '92',
            'CPF' => 'field_4040',
            'SEXO' => 'NULL',
            'CNPJ' => 'field_4041',
            'FLAG_CAD_ESTADUAL' => 1,            
            'FLAG_CAD_MUNICIPAL' => 0,            
            'FLAG_CAD_DISTRITAL' => 0,            
            'FLAG_CAD_NA_PONTOS_PONTOES' => 0,
            'FLAG_CAD_ES_PONTOS_PONTOES' => 0,            
            'FLAG_CAD_SNIIC' => 0,            
            'FLAG_CAD_SALIC' => 0,
            'FLAG_CAD_SICAB' => 0,
            'FLAG_CAD_OUTROS' => 0,
            'PESSOA_FISICA' => 'Pessoa Física',
            'PESSOA_JURIDICA' => 'Pessoa Jurídica',
            'COLETIVO' => 'Coletivo',
            // 'DIR_CSV' => 'csv92.csv',                           
        ],
        'depara_sexo' => [
            'MASCULINO' => 1,
            'FEMININO' => 2,
            'Masculino' => 1,
            'Feminino' => 2       
        ]
    ]    
];